version: "3"

services:
    db:
        image: postgres:12
        container_name: api-pgsql
        restart: always
        ports:
            - 5432:5432
        #volumes:
        #- ./bkp:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=logistica
            #- PGDATA=/var/lib/postgresql/data/pgdata

    pgadmin:
        image: dpage/pgadmin4
        container_name: api-pgsql
        ports:
            - 80:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=postgres
            - PGADMIN_DEFAULT_PASSWORD=postgres
        links:
            - db
